### ISSUE TITLE
[Bug] 安裝檔啟動持續加載(轉圈) 

### ISSUE THREAD

**Issue by Orenolamy** [RPMTW/launcher#260]
### Description of the error

啟動安裝檔時持續加載(如圖)，並未跳出遊戲輸出視窗(輸出遊戲日誌設定已開啟)，無法啟動遊戲。
已嘗試重啟動電腦，但無效。
每個安裝檔皆為相同狀況。
版本為最新版。
![image](https://user-images.githubusercontent.com/75882776/173105465-fc9b5803-46ac-4e59-98e2-94a5d9836de8.png)

### reproduce step

```bash
1.打開RPWLauncher啟動器
2.點擊任一安裝檔
3.點即啟動
4.持續轉圈
```

### expected-behavior

不再轉圈，啟動遊戲

### RPMLauncher version

1.0.7+913

### What is your operating system?

Windows 10

### RPMLauncher logs

```shell
[2022-06-11T00:02:20.448031] [1.0.7+913/0] [Info] Starting
[2022-06-11T00:02:20.476771] [1.0.7+913/0] [Info] OS Version: Windows 10+
[2022-06-11T00:02:20.871609] [1.0.7+913/0] [Info] Start Done
[2022-06-11T00:03:44.462795] [1.0.7+913/0] [Flutter Error] Null check operator used on a null value
#0      HeroController.didPop (package:flutter/src/widgets/heroes.dart:796)
#1      _NavigatorPopObservation.notify (package:flutter/src/widgets/navigator.dart:3152)
#2      _GrowableList.forEach (dart:core-patch/growable_array.dart:416)
#3      NavigatorState._flushObserverNotifications (package:flutter/src/widgets/navigator.dart:3979)
#4      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:3932)
#5      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:4910)
#6      _SettingScreenState.build.<anonymous closure> (package:rpmlauncher/screen/Settings.dart:90)
#7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:1005)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198)
#9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:613)
#10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:298)
#11     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:269)
#12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157)
#13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:449)
#14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:425)
#15     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:329)
#16     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380)
#17     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344)
#18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302)
#19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285)
#20     _rootRunUnary (dart:async/zone.dart:1442)
#21     _CustomZone.runUnary (dart:async/zone.dart:1335)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244)
#23     _invoke1 (dart:ui/hooks.dart:170)
#24     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331)
#25     _dispatchPointerDataPacket (dart:ui/hooks.dart:94)

[2022-06-11T00:04:00.446567] [1.0.7+913/0] [Info] Saving mod_info_index

[2022-06-11T00:04:00.453137] [1.0.7+913/0] [Unknown Error] Null check operator used on a null value
#0      HeroController.didPop (package:flutter/src/widgets/heroes.dart:796)
#1      _NavigatorPopObservation.notify (package:flutter/src/widgets/navigator.dart:3152)
#2      _GrowableList.forEach (dart:core-patch/growable_array.dart:416)
#3      NavigatorState._flushObserverNotifications (package:flutter/src/widgets/navigator.dart:3979)
#4      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:3932)
#5      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:4910)
#6      Data.init.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:rpmlauncher/util/data.dart:90)
#7      _rootRunUnary (dart:async/zone.dart:1434)
<asynchronous suspension>

[2022-06-11T00:04:02.307774] [1.0.7+913/0] [Info] Starting
[2022-06-11T00:04:02.336762] [1.0.7+913/0] [Info] OS Version: Windows 10+
[2022-06-11T00:04:02.603446] [1.0.7+913/0] [Info] Start Done
[2022-06-11T00:04:35.699177] [1.0.7+913/0] [Info] Saving mod_info_index

[2022-06-11T00:04:38.119503] [1.0.7+913/0] [Info] Starting
[2022-06-11T00:04:38.148920] [1.0.7+913/0] [Info] OS Version: Windows 10+
[2022-06-11T00:04:38.411451] [1.0.7+913/0] [Info] Start Done
[2022-06-11T00:05:13.889330] [1.0.7+913/0] [Info] Saving mod_info_index

[2022-06-11T00:07:09.564526] [1.0.7+913/0] [Info] Starting
[2022-06-11T00:07:09.596911] [1.0.7+913/0] [Info] OS Version: Windows 10+
[2022-06-11T00:07:09.895292] [1.0.7+913/0] [Info] Start Done
[2022-06-11T00:07:17.974360] [1.0.7+913/0] [Info] Saving mod_info_index

[2022-06-11T00:07:19.545772] [1.0.7+913/0] [Info] Starting
[2022-06-11T00:07:19.573657] [1.0.7+913/0] [Info] OS Version: Windows 10+
[2022-06-11T00:07:19.860284] [1.0.7+913/0] [Info] Start Done
[2022-06-11T00:07:32.294170] [1.0.7+913/0] [Info] Saving mod_info_index

[2022-06-11T00:09:18.488651] [1.0.7+913/0] [Info] Starting
[2022-06-11T00:09:18.516558] [1.0.7+913/0] [Info] OS Version: Windows 10+
[2022-06-11T00:09:18.782014] [1.0.7+913/0] [Info] Start Done
[2022-06-11T00:11:51.994011] [1.0.7+913/0] [Info] Saving mod_info_index

[2022-06-11T00:11:53.879184] [1.0.7+913/0] [Info] Starting
[2022-06-11T00:11:53.908915] [1.0.7+913/0] [Info] OS Version: Windows 10+
[2022-06-11T00:11:54.188273] [1.0.7+913/0] [Info] Start Done
```

**Comment by WANGCHIENCHIH** [comment]
我也遇到類似的問題
 我嘗試解決的方法
點選右上帳號，重新授權帳號後可成功啟動
菘菘可以檢視一下最近微軟合併基岩與Java之後驗證授權是否有改變，導致之前launcher的自動重新授權出包

**Comment by Orenolamy** [comment]
> 我也遇到了類似的 嘗試點選右上啟動 的解決方法，之後我 可以自動驗證授權授權後，可查看最近一次成功的計算與Java認證授權有不同，導致啟動前的重新啟動出包

解決了，非常感謝!!

**Comment by SiongSng** [comment]
此問題已於 https://github.com/RPMTW/RPMLauncher/commit/cfca476d9675673933e2ab57253cc04006302bc0 修復完成
