### ISSUE TITLE
安裝檔開啟崩潰

### ISSUE THREAD

**Issue by jlin53882** [RPMTW/launcher#91]
**描述錯誤**
安裝檔開啟崩潰

**重現步驟**
重現觸發這個錯誤的步驟：
( 範例 ):
1. 開啟 '1.17.1安裝檔出現錯誤1.16.5也會
4. 發現錯誤

**預期行為**
可以成功開啟

**截圖**
![螢幕擷取畫面 2021-10-15 172140](https://user-images.githubusercontent.com/76562059/137464573-85c25656-c2bf-40e8-a14b-1ccbf1f80618.png) 
第一張1.17.1
![螢幕擷取畫面 2021-10-15 172311](https://user-images.githubusercontent.com/76562059/137464772-7b5f75c8-80ce-4758-beba-165c871ccfe3.png)
第二張1.16.5

**RPMLauncher 日誌 (請務必填寫，檔案位於 `RPMLauncher資料儲存位置/logs/發生此錯誤時的時間.txt` )**
```
[2021-10-15T17:13:49.073203] [Info] Starting
[2021-10-15T17:13:49.074201] [Info] Start Done
[2021-10-15T17:13:51.499312] [Unknown Error] type 'Null' is not a subtype of type 'String'
#0      Updater.checkForUpdate.getVersionInfo (package:rpmlauncher/Utility/Updater.dart:110)
#1      Updater.checkForUpdate (package:rpmlauncher/Utility/Updater.dart:121)
<asynchronous suspension>

[2021-10-15T17:13:53.513229] [Info] Starting
[2021-10-15T17:13:53.514227] [Info] Start Done
[2021-10-15T17:17:29.450459] [Unknown Error] NoSuchMethodError: Class 'String' has no instance method 'transform'.
Receiver: "flutter: [Info] Starting\r\nflutter: [Info] Start Done\r\n"
Tried calling: transform(Instance of 'Utf8Decoder')
[2021-10-15T17:17:33.218158] [Info] Provider Create
[2021-10-15T17:17:39.609778] [Info] Starting
[2021-10-15T17:17:39.610776] [Info] Start Done
[2021-10-15T17:17:39.617757] [Info] Provider Create
[2021-10-15T17:18:00.268151] [Unknown Error] NoSuchMethodError: Class 'String' has no instance method 'transform'.
Receiver: "flutter: [Info] Starting\r\nflutter: [Info] Start Done\r\nflutter: [Info] Provider Create\r\nflutter: C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\versions\\1.16.5\\client.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\com/mojang/patchy/1.2.3/patchy-1.2.3.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\oshi-project/oshi-core/1.1/oshi-core-1.1.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\com/ibm/icu/icu4j/66.1/icu4j-66.1.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\com/google/guava/guava/21.0/guava-21.0.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\commons-io/commons-io/2.5/commons-io-2.5.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\commons-codec/commons-codec/1.10/commons-codec-1.10.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\com/google/code/gson/gson/2.8.0/gson-2.8.0.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\com/mojang/authlib/2.1.28/authlib-2.1.28.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\net/fabricmc/tiny-remapper/0.4.2/tiny-remapper-0.4.2.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\net/fabricmc/access-widener/1.0.0/access-widener-1.0.0.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\com/google/jimfs/jimfs/1.2-fabric/jimfs-1.2-fabric.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/ow2/asm/asm/9.1/asm-9.1.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\org/ow2/asm/asm-util/9.1/asm-util-9.1.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\net/fabricmc/intermediary/1.16.5/intermediary-1.16.5.jar;C:\\Users\\Jlin5\\Documents\\RPMLauncher\\data\\libraries\\net/fabricmc/fabric-loader/0.11.6/fabric-loader-0.11.6.jar\r\n"
Tried calling: transform(Instance of 'Utf8Decoder')
```

*辨識資訊 (請填寫以下資訊):**
 - 作業系統:windows
 - RPMLauncher 版本604
**其他說明**
無任何安裝模組

**Comment by SiongSng** [comment]
![圖片](https://user-images.githubusercontent.com/48402225/137494723-67812e19-9e32-43f9-a42d-e0d78167ca42.png)
我這裡測試正常 原版/Fabric 1.17.1/1.16.5皆可

**Comment by SiongSng** [comment]
你試試看刪除RPMTW的library與version資料夾
